// Generated by CoffeeScript 1.6.3
describe("conversion from water to coffee", function() {
  return it("converts water to coffee", function() {
    return expect(waterToCoffeeCalc(17)).toBe('1.00');
  });
});

describe("conversion from coffee to water", function() {
  return it("converts coffee to water", function() {
    return expect(coffeeToWaterCalc(1)).toBe('17.00');
  });
});
