// Generated by CoffeeScript 1.6.3
describe("coversion from water to coffee", function() {
  return it("coverts water to coffee", function() {
    return expect(waterToCoffeeCalc(17)).toBe('1.00');
  });
});
